services:
  frontend:
    build:
      context: .
      dockerfile: Containerfile
    container_name: gohealty-front
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true